name: python-plots
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyside6
  - netcdf4
  - scipy
  - matplotlib
  - cartopy
  - cartopy_offlinedata
  - toml
  - pip
  - pip:
      - julian
